import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      // Hydration error ফিক্স করার জন্য নিচের লাইনটি যোগ করা হয়েছে
      suppressHydrationWarning
    >
      <body 
        className="min-h-full flex flex-col"
        // বডি ট্যাগেও এটি যোগ করা নিরাপদ
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}